### ISSUE TITLE
v1.13.2 Crash when crafting gear from diamond gear in anvil on a server

### ISSUE THREAD

**Issue by sihrc** [Insane-96/CarbonadoMod#18]
Crafting carbonado gear through an anvil works fine in Single player, but crashes when in multiplayer on a forge server as soon as carbonado ore is placed in the second slot in the anvil with a diamond tool in the first slot.

No exception in server logs.

Client Logs:
```[23:36:39] [Client thread/ERROR]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class net.insane96mcp.carbonado.events.AnvilUpdate EventAnvilOuput(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
java.lang.NullPointerException
	at net.insane96mcp.carbonado.events.AnvilUpdate.EventAnvilOuput(AnvilUpdate.java:51)
	at net.minecraftforge.eventbus.ASMEventHandler_12_AnvilUpdate_EventAnvilOuput_AnvilUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:257)
	at net.minecraftforge.common.ForgeHooks.onAnvilChange(ForgeHooks.java:705)
	at net.minecraft.inventory.ContainerRepair.func_82848_d(ContainerRepair.java:138)
	at net.minecraft.inventory.ContainerRepair.func_75130_a(ContainerRepair.java:115)
	at net.minecraft.inventory.ContainerRepair$1.func_70296_d(ContainerRepair.java:29)
	at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:100)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:61)
	at net.minecraft.inventory.Container.func_75135_a(Container.java:479)
	at net.minecraft.inventory.ContainerRepair.func_82846_b(ContainerRepair.java:331)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:185)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:413)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:508)
	at net.minecraft.client.gui.inventory.GuiContainer.mouseClicked(GuiContainer.java:321)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper$$Lambda$1734/1691423523.run(Unknown Source)
	at net.minecraft.client.gui.GuiScreen.func_195121_a(GuiScreen.java:418)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:78)
	at net.minecraft.client.MouseHelper$$Lambda$1201/1501624947.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029)
	at net.minecraft.client.MainWindow.func_198086_a(SourceFile:309)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:817)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:358)
	at net.minecraft.client.main.Main.main(SourceFile:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$280/1948810915.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:56)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:42)

[23:36:41] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.crash.ReportedException: mouseClicked event handler
	at net.minecraft.client.gui.GuiScreen.func_195121_a(GuiScreen.java:425) ~[?:?]
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:78) ~[?:?]
	at net.minecraft.client.MouseHelper$$Lambda$1201/1501624947.invoke(Unknown Source) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.1.6.jar:build 14]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.1.6.jar:build 14]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3029) ~[lwjgl-glfw-3.1.6.jar:build 14]
	at net.minecraft.client.MainWindow.func_198086_a(SourceFile:309) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:817) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:358) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:144) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.13.2-25.0.92.jar:25.0]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$280/1948810915.call(Unknown Source) [forge-1.13.2-25.0.92.jar:25.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:19) [modlauncher-0.12.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:32) [modlauncher-0.12.1.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-0.12.1.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:56) [modlauncher-0.12.1.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:42) [modlauncher-0.12.1.jar:?]
Caused by: java.lang.NullPointerException
	at net.insane96mcp.carbonado.events.AnvilUpdate.EventAnvilOuput(AnvilUpdate.java:51) ~[?:1.6.0-mc1.13.x]
	at net.minecraftforge.eventbus.ASMEventHandler_12_AnvilUpdate_EventAnvilOuput_AnvilUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-0.8.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:257) ~[eventbus-0.8.0-service.jar:?]
	at net.minecraftforge.common.ForgeHooks.onAnvilChange(ForgeHooks.java:705) ~[?:?]
	at net.minecraft.inventory.ContainerRepair.func_82848_d(ContainerRepair.java:138) ~[?:?]
	at net.minecraft.inventory.ContainerRepair.func_75130_a(ContainerRepair.java:115) ~[?:?]
	at net.minecraft.inventory.ContainerRepair$1.func_70296_d(ContainerRepair.java:29) ~[?:?]
	at net.minecraft.inventory.InventoryBasic.func_70299_a(SourceFile:100) ~[?:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:61) ~[?:?]
	at net.minecraft.inventory.Container.func_75135_a(Container.java:479) ~[?:?]
	at net.minecraft.inventory.ContainerRepair.func_82846_b(ContainerRepair.java:331) ~[?:?]
	at net.minecraft.inventory.Container.func_184996_a(Container.java:185) ~[?:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:413) ~[?:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:508) ~[?:?]
	at net.minecraft.client.gui.inventory.GuiContainer.mouseClicked(GuiContainer.java:321) ~[?:?]
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:80) ~[?:?]
	at net.minecraft.client.MouseHelper$$Lambda$1734/1691423523.run(Unknown Source) ~[?:?]
	at net.minecraft.client.gui.GuiScreen.func_195121_a(GuiScreen.java:418) ~[?:?]
	... 20 more```

**Comment by sihrc** [comment]
Pretty new to modding, I've figured out how to run the client side from source, but trying to figure out how to run a server to debug. If you could point me in the right direction for reproducing the problem running from source, I'd be happy to send in a PR with a fix (if I find one).
